// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/infrastructure/repositories/hive_progress_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_arrow_maze/infrastructure/data_sources/local/hive_level_progress_data_source.dart'
    as _i2;
import 'package:flutter_arrow_maze/infrastructure/models/level_progress_hive_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HiveLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveLocalDataSource extends _i1.Mock
    implements _i2.HiveLocalDataSource {
  MockHiveLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LevelProgressHiveModel? getProgress(String? levelId) =>
      (super.noSuchMethod(Invocation.method(
        #getProgress,
        [levelId],
      )) as _i3.LevelProgressHiveModel?);

  @override
  _i4.Future<void> saveProgress(
    String? levelId,
    int? moveCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProgress,
          [
            levelId,
            moveCount,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markCompleted(String? levelId) => (super.noSuchMethod(
        Invocation.method(
          #markCompleted,
          [levelId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool isCompleted(String? levelId) => (super.noSuchMethod(
        Invocation.method(
          #isCompleted,
          [levelId],
        ),
        returnValue: false,
      ) as bool);
}
