// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/infrastructure/repositories/remote_level_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_arrow_maze/core/aspects/i_logger_service.dart' as _i5;
import 'package:flutter_arrow_maze/infrastructure/data_sources/local/level_cache_data_source.dart'
    as _i4;
import 'package:flutter_arrow_maze/infrastructure/data_sources/remote/level_remote_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LevelRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLevelRemoteDataSource extends _i1.Mock
    implements _i2.LevelRemoteDataSource {
  MockLevelRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<dynamic>> fetchLevelIds() => (super.noSuchMethod(
        Invocation.method(
          #fetchLevelIds,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> fetchLevel(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLevel,
          [id],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [LevelCacheDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLevelCacheDataSource extends _i1.Mock
    implements _i4.LevelCacheDataSource {
  MockLevelCacheDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> writeCatalog(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #writeCatalog,
          [ids],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String? readLevel(String? id) => (super.noSuchMethod(Invocation.method(
        #readLevel,
        [id],
      )) as String?);

  @override
  _i3.Future<void> writeLevel(
    String? id,
    String? rawJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeLevel,
          [
            id,
            rawJson,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ILoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoggerService extends _i1.Mock implements _i5.ILoggerService {
  MockILoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void log(
    String? message,
    String? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message,
    String? context, [
    Object? error,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [
            message,
            context,
            error,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warn(
    String? message,
    String? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #warn,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
