// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/application/use_cases/generate_board_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_arrow_maze/core/aspects/i_logger_service.dart' as _i4;
import 'package:flutter_arrow_maze/domain/arrows/entities/arrow_board.dart'
    as _i2;
import 'package:flutter_arrow_maze/domain/arrows/services/i_level_generator.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArrowBoard_0 extends _i1.SmartFake implements _i2.ArrowBoard {
  _FakeArrowBoard_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILevelGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockILevelGenerator extends _i1.Mock implements _i3.ILevelGenerator {
  MockILevelGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ArrowBoard generate({
    required int? cols,
    required int? rows,
    required int? arrowCount,
    required int? maxPathLen,
    int? seed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generate,
          [],
          {
            #cols: cols,
            #rows: rows,
            #arrowCount: arrowCount,
            #maxPathLen: maxPathLen,
            #seed: seed,
          },
        ),
        returnValue: _FakeArrowBoard_0(
          this,
          Invocation.method(
            #generate,
            [],
            {
              #cols: cols,
              #rows: rows,
              #arrowCount: arrowCount,
              #maxPathLen: maxPathLen,
              #seed: seed,
            },
          ),
        ),
      ) as _i2.ArrowBoard);
}

/// A class which mocks [ILoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoggerService extends _i1.Mock implements _i4.ILoggerService {
  MockILoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void log(
    String? message,
    String? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message,
    String? context, [
    Object? error,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [
            message,
            context,
            error,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warn(
    String? message,
    String? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #warn,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
