// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/application/use_cases/get_global_leaderboard_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_arrow_maze/domain/board/value_objects/level_id.dart'
    as _i8;
import 'package:flutter_arrow_maze/domain/leaderboard/entities/global_leaderboard.dart'
    as _i3;
import 'package:flutter_arrow_maze/domain/leaderboard/entities/leaderboard_entry.dart'
    as _i7;
import 'package:flutter_arrow_maze/domain/leaderboard/entities/score_entry.dart'
    as _i6;
import 'package:flutter_arrow_maze/domain/leaderboard/repositories/i_leaderboard_repository.dart'
    as _i4;
import 'package:flutter_arrow_maze/domain/leaderboard/value_objects/canonical_result.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCanonicalResult_0 extends _i1.SmartFake
    implements _i2.CanonicalResult {
  _FakeCanonicalResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalLeaderboard_1 extends _i1.SmartFake
    implements _i3.GlobalLeaderboard {
  _FakeGlobalLeaderboard_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILeaderboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILeaderboardRepository extends _i1.Mock
    implements _i4.ILeaderboardRepository {
  MockILeaderboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CanonicalResult> submitScore(_i6.ScoreEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitScore,
          [entry],
        ),
        returnValue:
            _i5.Future<_i2.CanonicalResult>.value(_FakeCanonicalResult_0(
          this,
          Invocation.method(
            #submitScore,
            [entry],
          ),
        )),
      ) as _i5.Future<_i2.CanonicalResult>);

  @override
  _i5.Future<List<_i7.LeaderboardEntry>> getLeaderboard(
    _i8.LevelId? levelId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaderboard,
          [levelId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i7.LeaderboardEntry>>.value(
            <_i7.LeaderboardEntry>[]),
      ) as _i5.Future<List<_i7.LeaderboardEntry>>);

  @override
  _i5.Future<_i3.GlobalLeaderboard> getGlobalLeaderboard() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalLeaderboard,
          [],
        ),
        returnValue:
            _i5.Future<_i3.GlobalLeaderboard>.value(_FakeGlobalLeaderboard_1(
          this,
          Invocation.method(
            #getGlobalLeaderboard,
            [],
          ),
        )),
      ) as _i5.Future<_i3.GlobalLeaderboard>);
}
