// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/application/use_cases/record_level_completion_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_arrow_maze/core/aspects/i_logger_service.dart' as _i7;
import 'package:flutter_arrow_maze/domain/board/repositories/i_level_progress_repository.dart'
    as _i2;
import 'package:flutter_arrow_maze/domain/board/value_objects/level_id.dart'
    as _i5;
import 'package:flutter_arrow_maze/domain/board/value_objects/level_progress.dart'
    as _i6;
import 'package:flutter_arrow_maze/domain/game_core/value_objects/move_count.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ILevelProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILevelProgressRepository extends _i1.Mock
    implements _i2.ILevelProgressRepository {
  MockILevelProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.MoveCount?> getProgress(_i5.LevelId? levelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [levelId],
        ),
        returnValue: _i3.Future<_i4.MoveCount?>.value(),
      ) as _i3.Future<_i4.MoveCount?>);

  @override
  _i3.Future<void> saveProgress(
    _i5.LevelId? levelId,
    _i4.MoveCount? moves,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProgress,
          [
            levelId,
            moves,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> markCompleted(_i5.LevelId? levelId) => (super.noSuchMethod(
        Invocation.method(
          #markCompleted,
          [levelId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isCompleted(_i5.LevelId? levelId) => (super.noSuchMethod(
        Invocation.method(
          #isCompleted,
          [levelId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i6.LevelProgress>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.LevelProgress>>.value(<_i6.LevelProgress>[]),
      ) as _i3.Future<List<_i6.LevelProgress>>);

  @override
  _i3.Future<void> upsertAll(List<_i6.LevelProgress>? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertAll,
          [progress],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ILoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoggerService extends _i1.Mock implements _i7.ILoggerService {
  MockILoggerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void log(
    String? message,
    String? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message,
    String? context, [
    Object? error,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [
            message,
            context,
            error,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warn(
    String? message,
    String? context,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #warn,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
