// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/application/use_cases/restore_session_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_arrow_maze/domain/auth/repositories/i_auth_token_storage.dart'
    as _i2;
import 'package:flutter_arrow_maze/domain/auth/value_objects/auth_token.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IAuthTokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthTokenStorage extends _i1.Mock implements _i2.IAuthTokenStorage {
  MockIAuthTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(_i4.AuthToken? token) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.AuthToken?> read() => (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
        ),
        returnValue: _i3.Future<_i4.AuthToken?>.value(),
      ) as _i3.Future<_i4.AuthToken?>);

  @override
  _i3.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
