// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_arrow_maze/test/presentation/auth/screens/register_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_arrow_maze/domain/auth/failures/auth_failure.dart'
    as _i5;
import 'package:flutter_arrow_maze/domain/auth/repositories/i_auth_repository.dart'
    as _i3;
import 'package:flutter_arrow_maze/domain/auth/repositories/i_auth_token_storage.dart'
    as _i8;
import 'package:flutter_arrow_maze/domain/auth/value_objects/auth_token.dart'
    as _i6;
import 'package:flutter_arrow_maze/domain/auth/value_objects/email.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AuthToken>> login(
    _i7.Email? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AuthToken>>.value(
                _FakeEither_0<_i5.AuthFailure, _i6.AuthToken>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AuthToken>>);

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AuthToken>> register(
    _i7.Email? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AuthToken>>.value(
                _FakeEither_0<_i5.AuthFailure, _i6.AuthToken>(
          this,
          Invocation.method(
            #register,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i6.AuthToken>>);
}

/// A class which mocks [IAuthTokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthTokenStorage extends _i1.Mock implements _i8.IAuthTokenStorage {
  MockIAuthTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save(_i6.AuthToken? token) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.AuthToken?> read() => (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
        ),
        returnValue: _i4.Future<_i6.AuthToken?>.value(),
      ) as _i4.Future<_i6.AuthToken?>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
